version = "0.1"
license = "LGPL-3"
date = "26 May 2015"
date2 = "26 May 2015"
package = "noexamples"
title = "Error Package"
authors = "Pedro R. Andrade"
contact = "pedro.andrade@inpe.br"
content = [[A package that does not have the examples directory.]]
