version = "0.1"
license = "LGPL-3"
date = "26 May 2015"
date2 = "26 May 2015"
package = "onerrorbuild"
title = "Error Package"
authors = "Pedro R. Andrade"
contact = "pedro.andrade@inpe.br"
content = [[This package describe the errors built by the -build executions of TerraME. It contains exactly one eror for each verification of -build.]]
