version = "0.1"
license = "LGPL-3"
date = "26 May 2015"
date2 = "26 May 2015"
package = "nolua"
title = "Error Package"
authors = "Pedro R. Andrade"
contact = "pedro.andrade@inpe.br"
content = [[Package that does not contain a lua directory.]]
